name: Build Linux ARM

on: [push, pull_request]

jobs:
  linux-arm-gcc:
    runs-on: ubuntu-latest
    container:
      image: kubasejdak/arm-linux-gnueabihf-gcc:${{ matrix.gcc }}
    strategy:
      matrix:
        gcc: [9, 8]
        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v1

    - name: Build application
      run: |
        mkdir build
        cd build

        conan install .. --build missing -s build_type=${{ matrix.mode }}
        cmake .. -DPLATFORM=linux-arm -DTOOLCHAIN=arm-linux-gnueabihf-gcc-${{ matrix.gcc }} -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
        make

  linux-arm-clang:
    runs-on: ubuntu-latest
    container:
      image: kubasejdak/arm-linux-gnueabihf-clang:${{ matrix.clang }}
    strategy:
      matrix:
        clang: [9, 8, 7]
        mode: [Debug, Release]

    steps:
      - uses: actions/checkout@v1

      - name: Build application
        run: |
          mkdir build
          cd build

          conan install .. --build missing -s build_type=${{ matrix.mode }}
          cmake .. -DPLATFORM=linux-arm -DTOOLCHAIN=arm-linux-gnueabihf-clang-${{ matrix.clang }} -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          make
